navbar:
  visiable: auto # always, auto
  logo: 
    img: 
    icon: 
    title: 三峡大学水枝夏动漫社
  menu:
    - name: 主页
      icon: fas fa-rss
      url: /
    - name: 主要社员
      icon: fas fa-link
      url: friends/
    - name: 组织机构
      icon: fas fa-info-circle
      url: about/
  search: 搜索
  
pages: 
#  friends: # 友链页面配置
#    layout_scheme: traditional

plugins: 

custom_css:
  font_smoothing: true # 抗锯齿
  navbar:
    height: 64px
    effect: [shadow, blur]